name: fk_core_package
description: The common core for Flutter projects
version: 1.1.0
authors: Thai Nguyen

environment:
  sdk: ">= 2.8.0 < 3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ### Third parties
  rxdart: ^0.25.0
  json_serializable: ^3.5.1
  logger: ^0.9.4
  flutter_progress_hud: ^1.0.3
  fluttertoast: ^7.1.6
  fluro: ^1.7.8
  dio: ^3.0.10
  after_layout: ^1.0.7+2
  flutter_bloc: ^6.1.1
  flutter_device_type: ^0.3.2

